import {
  Calculator,
  Activity,
  Stethoscope,
  Scale,
  MapPin,
  Settings,
  FileText,
  Link as LinkIcon,
  ShoppingCart,
  BarChart,
  Briefcase,
  Building,
  Home,
  Wrench,
  Search,
  Target,
  Shield,
  TrendingUp,
  Users,
  Zap,
  ChevronRight,
  ArrowRight,
  Map as MapIcon,
  Phone,
  Trophy,
  Award,
  Globe,
  Lightbulb,
  Building2,
  CheckCircle,
  Play
} from 'lucide-react';
import React from 'react';

export const iconMap: Record<string, React.ElementType> = {
  calculator: Calculator,
  activity: Activity,
  stethoscope: Stethoscope,
  scale: Scale,
  'map-pin': MapPin,
  settings: Settings,
  'file-text': FileText,
  link: LinkIcon,
  'shopping-cart': ShoppingCart,
  'bar-chart': BarChart,
  briefcase: Briefcase,
  building: Building,
  home: Home,
  wrench: Wrench,
  search: Search,
  target: Target,
  shield: Shield,
  'trending-up': TrendingUp,
  users: Users,
  zap: Zap,
  'chevron-right': ChevronRight,
  'arrow-right': ArrowRight,
  map: MapIcon,
  phone: Phone,
  trophy: Trophy,
  award: Award,
  globe: Globe,
  lightbulb: Lightbulb,
  building2: Building2,
  'check-circle': CheckCircle,
  play: Play
};

export const getIcon = (name: string) => {
  return iconMap[name.toLowerCase()] || Zap;
};
